# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_centralwidget_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.frame_centralwidget_layout.setContentsMargins(0, 0, 0, 0)
        self.frame_centralwidget_layout.setSpacing(0)
        self.frame_centralwidget_layout.setObjectName("frame_centralwidget_layout")
        self.frame_main_bg = QtWidgets.QFrame(self.centralwidget)
        self.frame_main_bg.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(234, 234, 234);\n"
"")
        self.frame_main_bg.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_main_bg.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_main_bg.setLineWidth(1)
        self.frame_main_bg.setMidLineWidth(0)
        self.frame_main_bg.setObjectName("frame_main_bg")
        self.frame_main_bg_layout = QtWidgets.QVBoxLayout(self.frame_main_bg)
        self.frame_main_bg_layout.setContentsMargins(5, 5, 5, 5)
        self.frame_main_bg_layout.setSpacing(5)
        self.frame_main_bg_layout.setObjectName("frame_main_bg_layout")
        self.frame_title_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_title_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_title_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_title_bar.setStyleSheet("")
        self.frame_title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title_bar.setObjectName("frame_title_bar")
        self.title_bar_layout = QtWidgets.QHBoxLayout(self.frame_title_bar)
        self.title_bar_layout.setContentsMargins(0, 0, 0, 0)
        self.title_bar_layout.setSpacing(0)
        self.title_bar_layout.setObjectName("title_bar_layout")
        self.frame_title = QtWidgets.QFrame(self.frame_title_bar)
        self.frame_title.setStyleSheet("background-color: none;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.title_layout = QtWidgets.QHBoxLayout(self.frame_title)
        self.title_layout.setContentsMargins(5, 0, 0, 0)
        self.title_layout.setSpacing(0)
        self.title_layout.setObjectName("title_layout")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(52, 217, 182);")
        self.label_title.setObjectName("label_title")
        self.title_layout.addWidget(self.label_title)
        self.title_bar_layout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.frame_title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setStyleSheet("background-color: none;")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.btn_layout = QtWidgets.QHBoxLayout(self.frame_btns)
        self.btn_layout.setContentsMargins(0, 0, 0, 0)
        self.btn_layout.setSpacing(0)
        self.btn_layout.setObjectName("btn_layout")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 170, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 170, 0);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_layout.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_close.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 60, 105);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_layout.addWidget(self.btn_close)
        self.title_bar_layout.addWidget(self.frame_btns)
        self.frame_main_bg_layout.addWidget(self.frame_title_bar)
        self.frame_content_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_content_bar.setAccessibleName("")
        self.frame_content_bar.setStyleSheet("border-radius: 1px;\n"
"")
        self.frame_content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_bar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_content_bar.setLineWidth(1)
        self.frame_content_bar.setMidLineWidth(0)
        self.frame_content_bar.setObjectName("frame_content_bar")
        self.frame_contentBar_layout = QtWidgets.QHBoxLayout(self.frame_content_bar)
        self.frame_contentBar_layout.setContentsMargins(5, 5, 5, 5)
        self.frame_contentBar_layout.setSpacing(5)
        self.frame_contentBar_layout.setObjectName("frame_contentBar_layout")
        self.frame_leftBody = QtWidgets.QFrame(self.frame_content_bar)
        self.frame_leftBody.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_leftBody.setStyleSheet("background-color: rgb(46, 64, 87);\n"
"color: white;\n"
"border: outset;\n"
"border-radius: 5px;")
        self.frame_leftBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_leftBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_leftBody.setLineWidth(10)
        self.frame_leftBody.setMidLineWidth(10)
        self.frame_leftBody.setObjectName("frame_leftBody")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_leftBody)
        self.verticalLayout_2.setContentsMargins(20, 30, 20, 30)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.frame_leftBody)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777214, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("background-color: rgb(138, 155, 197);\n"
"border-radius: 10px;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.frame = QtWidgets.QFrame(self.frame_leftBody)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(20, 30, 20, 0)
        self.gridLayout_5.setHorizontalSpacing(10)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.addressLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        self.gridLayout_5.addWidget(self.addressLabel, 2, 0, 1, 1)
        self.ContactEdit = QtWidgets.QLineEdit(self.frame)
        self.ContactEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(229, 230, 220);\n"
"    color: rgb(0, 71, 104);\n"
"    border-style: outset;\n"
"    border-width:2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(233, 231, 255);\n"
"}")
        self.ContactEdit.setObjectName("ContactEdit")
        self.gridLayout_5.addWidget(self.ContactEdit, 3, 1, 1, 1)
        self.ageLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.gridLayout_5.addWidget(self.ageLabel, 1, 0, 1, 1)
        self.contactLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.contactLabel.setFont(font)
        self.contactLabel.setObjectName("contactLabel")
        self.gridLayout_5.addWidget(self.contactLabel, 3, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.frame)
        self.nameEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(229, 230, 220);\n"
"    color: rgb(0, 71, 104);\n"
"    border-style: outset;\n"
"    border-width:2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(233, 231, 255);\n"
"}")
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_5.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.ageEdit = QtWidgets.QLineEdit(self.frame)
        self.ageEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(229, 230, 220);\n"
"    color: rgb(0, 71, 104);\n"
"    border-style: outset;\n"
"    border-width:2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(233, 231, 255);\n"
"}")
        self.ageEdit.setText("")
        self.ageEdit.setObjectName("ageEdit")
        self.gridLayout_5.addWidget(self.ageEdit, 1, 1, 1, 1)
        self.addressEdit = QtWidgets.QLineEdit(self.frame)
        self.addressEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(229, 230, 220);\n"
"    color: rgb(0, 71, 104);\n"
"    border-style: outset;\n"
"    border-width:2px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(233, 231, 255);\n"
"}")
        self.addressEdit.setObjectName("addressEdit")
        self.gridLayout_5.addWidget(self.addressEdit, 2, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_5.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame1 = QtWidgets.QFrame(self.frame_leftBody)
        self.frame1.setMinimumSize(QtCore.QSize(0, 80))
        self.frame1.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame1.setObjectName("frame1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame2 = QtWidgets.QFrame(self.frame1)
        self.frame2.setObjectName("frame2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame2)
        self.gridLayout.setContentsMargins(20, -1, -1, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.checkUpBox = QtWidgets.QCheckBox(self.frame2)
        self.checkUpBox.setMinimumSize(QtCore.QSize(150, 0))
        self.checkUpBox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkUpBox.setFont(font)
        self.checkUpBox.setObjectName("checkUpBox")
        self.gridLayout.addWidget(self.checkUpBox, 0, 0, 1, 1)
        self.vaccineBox = QtWidgets.QCheckBox(self.frame2)
        self.vaccineBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.vaccineBox.setFont(font)
        self.vaccineBox.setObjectName("vaccineBox")
        self.gridLayout.addWidget(self.vaccineBox, 0, 1, 1, 1)
        self.dentalBox = QtWidgets.QCheckBox(self.frame2)
        self.dentalBox.setMinimumSize(QtCore.QSize(150, 0))
        self.dentalBox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.dentalBox.setFont(font)
        self.dentalBox.setObjectName("dentalBox")
        self.gridLayout.addWidget(self.dentalBox, 1, 0, 1, 1)
        self.priorityBox = QtWidgets.QCheckBox(self.frame2)
        self.priorityBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.priorityBox.setFont(font)
        self.priorityBox.setObjectName("priorityBox")
        self.gridLayout.addWidget(self.priorityBox, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame1)
        self.frame3 = QtWidgets.QFrame(self.frame_leftBody)
        self.frame3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame3.setObjectName("frame3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveBtn = QtWidgets.QPushButton(self.frame3)
        self.saveBtn.setMinimumSize(QtCore.QSize(90, 0))
        self.saveBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"}")
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.saveAndPrintBtn = QtWidgets.QPushButton(self.frame3)
        self.saveAndPrintBtn.setMinimumSize(QtCore.QSize(90, 0))
        self.saveAndPrintBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveAndPrintBtn.setFont(font)
        self.saveAndPrintBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"}")
        self.saveAndPrintBtn.setDefault(False)
        self.saveAndPrintBtn.setFlat(False)
        self.saveAndPrintBtn.setObjectName("saveAndPrintBtn")
        self.horizontalLayout.addWidget(self.saveAndPrintBtn)
        self.verticalLayout_2.addWidget(self.frame3)
        self.frame_contentBar_layout.addWidget(self.frame_leftBody)
        self.frame_rightBody = QtWidgets.QFrame(self.frame_content_bar)
        self.frame_rightBody.setStyleSheet("background-color: rgb(74, 74, 111);\n"
"border-radius: 5px;")
        self.frame_rightBody.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_rightBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rightBody.setObjectName("frame_rightBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_rightBody)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_rightBody)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.checkUpTab = QtWidgets.QWidget()
        self.checkUpTab.setMaximumSize(QtCore.QSize(16777215, 16777209))
        self.checkUpTab.setStyleSheet("background-color: none;\n"
"border-raidus: 5px;")
        self.checkUpTab.setObjectName("checkUpTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.checkUpTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkUpTable = QtWidgets.QTableWidget(self.checkUpTab)
        self.checkUpTable.setRowCount(150)
        self.checkUpTable.setObjectName("checkUpTable")
        self.checkUpTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.checkUpTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkUpTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkUpTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkUpTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkUpTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkUpTable.setHorizontalHeaderItem(5, item)
        self.checkUpTable.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.checkUpTable, 0, 0, 1, 1)
        self.checkUpNew = QtWidgets.QPushButton(self.checkUpTab)
        self.checkUpNew.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkUpNew.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"}")
        self.checkUpNew.setObjectName("checkUpNew")
        self.gridLayout_2.addWidget(self.checkUpNew, 2, 0, 1, 1)
        self.tabWidget.addTab(self.checkUpTab, "")
        self.vaccineTab = QtWidgets.QWidget()
        self.vaccineTab.setStyleSheet("background-color: none;\n"
"border-raidus: 5px;")
        self.vaccineTab.setObjectName("vaccineTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.vaccineTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vaccineNew = QtWidgets.QPushButton(self.vaccineTab)
        self.vaccineNew.setMaximumSize(QtCore.QSize(150, 16777215))
        self.vaccineNew.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"}")
        self.vaccineNew.setObjectName("vaccineNew")
        self.gridLayout_3.addWidget(self.vaccineNew, 1, 0, 1, 1)
        self.vaccineTable = QtWidgets.QTableWidget(self.vaccineTab)
        self.vaccineTable.setRowCount(150)
        self.vaccineTable.setObjectName("vaccineTable")
        self.vaccineTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.vaccineTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vaccineTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vaccineTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.vaccineTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.vaccineTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.vaccineTable.setHorizontalHeaderItem(5, item)
        self.vaccineTable.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.vaccineTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.vaccineTab, "")
        self.dentalTab = QtWidgets.QWidget()
        self.dentalTab.setStyleSheet("background-color: none;\n"
"border-raidus: 5px;")
        self.dentalTab.setObjectName("dentalTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dentalTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dentalNew = QtWidgets.QPushButton(self.dentalTab)
        self.dentalNew.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dentalNew.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"}")
        self.dentalNew.setObjectName("dentalNew")
        self.gridLayout_4.addWidget(self.dentalNew, 1, 0, 1, 1)
        self.dentalTable = QtWidgets.QTableWidget(self.dentalTab)
        self.dentalTable.setRowCount(150)
        self.dentalTable.setObjectName("dentalTable")
        self.dentalTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.dentalTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dentalTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dentalTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dentalTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dentalTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dentalTable.setHorizontalHeaderItem(5, item)
        self.dentalTable.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.dentalTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dentalTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame_contentBar_layout.addWidget(self.frame_rightBody)
        self.frame_main_bg_layout.addWidget(self.frame_content_bar)
        self.label_credits = QtWidgets.QLabel(self.frame_main_bg)
        self.label_credits.setStyleSheet("color: rgb(99, 99, 149);")
        self.label_credits.setObjectName("label_credits")
        self.frame_main_bg_layout.addWidget(self.label_credits)
        self.frame_etc_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_etc_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_etc_bar.setStyleSheet("")
        self.frame_etc_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_etc_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_etc_bar.setObjectName("frame_etc_bar")
        self.etc_layout = QtWidgets.QHBoxLayout(self.frame_etc_bar)
        self.etc_layout.setContentsMargins(0, 0, 0, 5)
        self.etc_layout.setSpacing(0)
        self.etc_layout.setObjectName("etc_layout")
        self.frame_credits = QtWidgets.QFrame(self.frame_etc_bar)
        self.frame_credits.setStyleSheet("background-color: none;")
        self.frame_credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_credits.setObjectName("frame_credits")
        self.credits_layout = QtWidgets.QHBoxLayout(self.frame_credits)
        self.credits_layout.setContentsMargins(5, -1, -1, 0)
        self.credits_layout.setObjectName("credits_layout")
        self.etc_layout.addWidget(self.frame_credits)
        self.frame_grip = QtWidgets.QFrame(self.frame_etc_bar)
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("background-color: none; padding: 5px; ")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.etc_layout.addWidget(self.frame_grip)
        self.frame_main_bg_layout.addWidget(self.frame_etc_bar)
        self.frame_centralwidget_layout.addWidget(self.frame_main_bg)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btn_close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Patients Information Window"))
        self.titleLabel.setText(_translate("MainWindow", "Patients Information"))
        self.addressLabel.setText(_translate("MainWindow", "Address"))
        self.ageLabel.setText(_translate("MainWindow", "Age"))
        self.contactLabel.setText(_translate("MainWindow", "Contact"))
        self.nameLabel.setText(_translate("MainWindow", "Full Name"))
        self.checkUpBox.setText(_translate("MainWindow", "Check Up"))
        self.vaccineBox.setText(_translate("MainWindow", "Vaccine"))
        self.dentalBox.setText(_translate("MainWindow", "Dental"))
        self.priorityBox.setText(_translate("MainWindow", "Priority"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.saveAndPrintBtn.setText(_translate("MainWindow", "Save & Print"))
        item = self.checkUpTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ticket Number"))
        item = self.checkUpTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.checkUpTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Age"))
        item = self.checkUpTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.checkUpTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Contact"))
        item = self.checkUpTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date and Time"))
        self.checkUpNew.setText(_translate("MainWindow", "New Record"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.checkUpTab), _translate("MainWindow", "Check Up"))
        self.vaccineNew.setText(_translate("MainWindow", "New Record"))
        item = self.vaccineTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ticket Number"))
        item = self.vaccineTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.vaccineTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Age"))
        item = self.vaccineTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.vaccineTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Contact"))
        item = self.vaccineTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date and Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vaccineTab), _translate("MainWindow", "Vaccine"))
        self.dentalNew.setText(_translate("MainWindow", "New Record"))
        item = self.dentalTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ticket Number"))
        item = self.dentalTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.dentalTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Age"))
        item = self.dentalTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.dentalTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Contact"))
        item = self.dentalTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date and Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dentalTab), _translate("MainWindow", "Dental"))
        self.label_credits.setText(_translate("MainWindow", "Powered By: Python"))

