# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 905)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_centralwidget_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.frame_centralwidget_layout.setContentsMargins(0, 0, 0, 0)
        self.frame_centralwidget_layout.setSpacing(0)
        self.frame_centralwidget_layout.setObjectName("frame_centralwidget_layout")
        self.frame_main_bg = QtWidgets.QFrame(self.centralwidget)
        self.frame_main_bg.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(234, 234, 234);\n"
"")
        self.frame_main_bg.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_main_bg.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_main_bg.setLineWidth(1)
        self.frame_main_bg.setMidLineWidth(0)
        self.frame_main_bg.setObjectName("frame_main_bg")
        self.frame_main_bg_layout = QtWidgets.QVBoxLayout(self.frame_main_bg)
        self.frame_main_bg_layout.setContentsMargins(5, 5, 5, 5)
        self.frame_main_bg_layout.setSpacing(5)
        self.frame_main_bg_layout.setObjectName("frame_main_bg_layout")
        self.frame_title_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_title_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_title_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_title_bar.setStyleSheet("")
        self.frame_title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title_bar.setObjectName("frame_title_bar")
        self.title_bar_layout = QtWidgets.QHBoxLayout(self.frame_title_bar)
        self.title_bar_layout.setContentsMargins(0, 0, 0, 0)
        self.title_bar_layout.setSpacing(0)
        self.title_bar_layout.setObjectName("title_bar_layout")
        self.frame_title = QtWidgets.QFrame(self.frame_title_bar)
        self.frame_title.setStyleSheet("background-color: none;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.title_layout = QtWidgets.QHBoxLayout(self.frame_title)
        self.title_layout.setContentsMargins(5, 0, 0, 0)
        self.title_layout.setSpacing(0)
        self.title_layout.setObjectName("title_layout")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(52, 217, 182);")
        self.label_title.setObjectName("label_title")
        self.title_layout.addWidget(self.label_title)
        self.title_bar_layout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.frame_title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setStyleSheet("background-color: none;")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.btn_layout = QtWidgets.QHBoxLayout(self.frame_btns)
        self.btn_layout.setContentsMargins(0, 0, 0, 0)
        self.btn_layout.setSpacing(0)
        self.btn_layout.setObjectName("btn_layout")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 170, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 170, 0);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_layout.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_close.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 60, 105);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_layout.addWidget(self.btn_close)
        self.title_bar_layout.addWidget(self.frame_btns)
        self.frame_main_bg_layout.addWidget(self.frame_title_bar)
        self.frame_content_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_content_bar.setAccessibleName("")
        self.frame_content_bar.setStyleSheet("border-radius: 1px;\n"
"")
        self.frame_content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_bar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_content_bar.setLineWidth(1)
        self.frame_content_bar.setMidLineWidth(0)
        self.frame_content_bar.setObjectName("frame_content_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_content_bar)
        self.horizontalLayout.setContentsMargins(-1, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_content_bar)
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setStyleSheet("background-color: rgb(68, 68, 102);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_buttons = QtWidgets.QFrame(self.frame_content_bar)
        self.frame_buttons.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_buttons.setObjectName("frame_buttons")
        self.label = QtWidgets.QLabel(self.frame_buttons)
        self.label.setGeometry(QtCore.QRect(40, 30, 1000, 100))
        self.label.setMinimumSize(QtCore.QSize(1000, 100))
        self.label.setMaximumSize(QtCore.QSize(600, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame_buttons)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 300, 771, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vaccineBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.vaccineBtn.setMinimumSize(QtCore.QSize(250, 150))
        self.vaccineBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.vaccineBtn.setFont(font)
        self.vaccineBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vaccineBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"    color: blue;\n"
"}")
        self.vaccineBtn.setObjectName("vaccineBtn")
        self.gridLayout.addWidget(self.vaccineBtn, 0, 1, 1, 1)
        self.checkUpBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.checkUpBtn.setMinimumSize(QtCore.QSize(250, 150))
        self.checkUpBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.checkUpBtn.setFont(font)
        self.checkUpBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkUpBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"    color: blue;\n"
"}")
        self.checkUpBtn.setObjectName("checkUpBtn")
        self.gridLayout.addWidget(self.checkUpBtn, 0, 0, 1, 1)
        self.dentalBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.dentalBtn.setMinimumSize(QtCore.QSize(250, 150))
        self.dentalBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.dentalBtn.setFont(font)
        self.dentalBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dentalBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"    color: blue;\n"
"}")
        self.dentalBtn.setObjectName("dentalBtn")
        self.gridLayout.addWidget(self.dentalBtn, 1, 0, 1, 1)
        self.priorityBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.priorityBtn.setMinimumSize(QtCore.QSize(250, 150))
        self.priorityBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.priorityBtn.setFont(font)
        self.priorityBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.priorityBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 42, 62);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(170, 0, 0, 150);\n"
"    color: red;\n"
"}")
        self.priorityBtn.setObjectName("priorityBtn")
        self.gridLayout.addWidget(self.priorityBtn, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_buttons)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 160, 961, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(170, 42, 62);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_buttons)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 780, 306, 16))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(100)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cuTicket = QtWidgets.QTextEdit(self.layoutWidget2)
        self.cuTicket.setMinimumSize(QtCore.QSize(0, 0))
        self.cuTicket.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cuTicket.setFont(font)
        self.cuTicket.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.cuTicket.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cuTicket.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: green;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.cuTicket.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cuTicket.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cuTicket.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cuTicket.setReadOnly(True)
        self.cuTicket.setObjectName("cuTicket")
        self.horizontalLayout_3.addWidget(self.cuTicket)
        self.vcTicket = QtWidgets.QTextEdit(self.layoutWidget2)
        self.vcTicket.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.vcTicket.setFont(font)
        self.vcTicket.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.vcTicket.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.vcTicket.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: green;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.vcTicket.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vcTicket.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vcTicket.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vcTicket.setReadOnly(True)
        self.vcTicket.setObjectName("vcTicket")
        self.horizontalLayout_3.addWidget(self.vcTicket)
        self.dtTicket = QtWidgets.QTextEdit(self.layoutWidget2)
        self.dtTicket.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dtTicket.setFont(font)
        self.dtTicket.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.dtTicket.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dtTicket.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: green;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.dtTicket.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dtTicket.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dtTicket.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dtTicket.setReadOnly(True)
        self.dtTicket.setObjectName("dtTicket")
        self.horizontalLayout_3.addWidget(self.dtTicket)
        self.ptTicket = QtWidgets.QTextEdit(self.layoutWidget2)
        self.ptTicket.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ptTicket.setFont(font)
        self.ptTicket.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.ptTicket.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ptTicket.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: red;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.ptTicket.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ptTicket.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ptTicket.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ptTicket.setReadOnly(True)
        self.ptTicket.setObjectName("ptTicket")
        self.horizontalLayout_3.addWidget(self.ptTicket)
        self.label_6 = QtWidgets.QLabel(self.frame_buttons)
        self.label_6.setGeometry(QtCore.QRect(950, 740, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-color: black;\n"
"mid-width: 10px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_buttons)
        self.layoutWidget_2.setGeometry(QtCore.QRect(90, 220, 891, 102))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(100)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cuTicket1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.cuTicket1.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.cuTicket1.setFont(font)
        self.cuTicket1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: green;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.cuTicket1.setText("")
        self.cuTicket1.setAlignment(QtCore.Qt.AlignCenter)
        self.cuTicket1.setObjectName("cuTicket1")
        self.horizontalLayout_6.addWidget(self.cuTicket1)
        self.vcTicket1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.vcTicket1.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.vcTicket1.setFont(font)
        self.vcTicket1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: green;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.vcTicket1.setText("")
        self.vcTicket1.setAlignment(QtCore.Qt.AlignCenter)
        self.vcTicket1.setObjectName("vcTicket1")
        self.horizontalLayout_6.addWidget(self.vcTicket1)
        self.dtTicket1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.dtTicket1.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.dtTicket1.setFont(font)
        self.dtTicket1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: green;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.dtTicket1.setText("")
        self.dtTicket1.setAlignment(QtCore.Qt.AlignCenter)
        self.dtTicket1.setObjectName("dtTicket1")
        self.horizontalLayout_6.addWidget(self.dtTicket1)
        self.ptTicket1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.ptTicket1.setMaximumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.ptTicket1.setFont(font)
        self.ptTicket1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: green;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.ptTicket1.setText("")
        self.ptTicket1.setAlignment(QtCore.Qt.AlignCenter)
        self.ptTicket1.setObjectName("ptTicket1")
        self.horizontalLayout_6.addWidget(self.ptTicket1)
        self.dateTime = QtWidgets.QLabel(self.frame_buttons)
        self.dateTime.setGeometry(QtCore.QRect(940, 770, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dateTime.setFont(font)
        self.dateTime.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: green;\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.dateTime.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dateTime.setText("")
        self.dateTime.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTime.setObjectName("dateTime")
        self.horizontalLayout.addWidget(self.frame_buttons)
        self.frame_3 = QtWidgets.QFrame(self.frame_content_bar)
        self.frame_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(68, 68, 102);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_main_bg_layout.addWidget(self.frame_content_bar)
        self.frame_etc_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_etc_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_etc_bar.setStyleSheet("")
        self.frame_etc_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_etc_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_etc_bar.setObjectName("frame_etc_bar")
        self.etc_layout = QtWidgets.QHBoxLayout(self.frame_etc_bar)
        self.etc_layout.setContentsMargins(0, 0, 0, 5)
        self.etc_layout.setSpacing(0)
        self.etc_layout.setObjectName("etc_layout")
        self.frame_credits = QtWidgets.QFrame(self.frame_etc_bar)
        self.frame_credits.setStyleSheet("background-color: none;")
        self.frame_credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_credits.setObjectName("frame_credits")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_credits)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_credits = QtWidgets.QLabel(self.frame_credits)
        self.label_credits.setStyleSheet("color: rgb(99, 99, 149);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_2.addWidget(self.label_credits)
        self.etc_layout.addWidget(self.frame_credits)
        self.frame_grip = QtWidgets.QFrame(self.frame_etc_bar)
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("background-color: none; padding: 5px; ")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.etc_layout.addWidget(self.frame_grip)
        self.frame_main_bg_layout.addWidget(self.frame_etc_bar)
        self.frame_centralwidget_layout.addWidget(self.frame_main_bg)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Ticket System"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Bagbaguin Health Center and Lying-In Clinic</p></body></html>"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Bagbaguin Health Center and Lying - In Clinic"))
        self.vaccineBtn.setText(_translate("MainWindow", "Vaccine"))
        self.checkUpBtn.setText(_translate("MainWindow", "Check Up"))
        self.dentalBtn.setText(_translate("MainWindow", "Dental"))
        self.priorityBtn.setText(_translate("MainWindow", "Priority"))
        self.label_2.setText(_translate("MainWindow", "Check Up"))
        self.label_3.setText(_translate("MainWindow", "Vaccine"))
        self.label_5.setText(_translate("MainWindow", "Dental"))
        self.label_4.setText(_translate("MainWindow", "Priority"))
        self.cuTicket.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:10px; margin-bottom:10px; margin-left:30px; margin-right:30px; -qt-block-indent:0; text-indent:0px; font-size:28pt;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Time Now"))
        self.label_credits.setText(_translate("MainWindow", "Powered By: Python"))

