# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_centralwidget_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.frame_centralwidget_layout.setContentsMargins(0, 0, 0, 0)
        self.frame_centralwidget_layout.setSpacing(0)
        self.frame_centralwidget_layout.setObjectName("frame_centralwidget_layout")
        self.frame_main_bg = QtWidgets.QFrame(self.centralwidget)
        self.frame_main_bg.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(234, 234, 234);\n"
"")
        self.frame_main_bg.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_main_bg.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_main_bg.setLineWidth(1)
        self.frame_main_bg.setMidLineWidth(0)
        self.frame_main_bg.setObjectName("frame_main_bg")
        self.frame_main_bg_layout = QtWidgets.QVBoxLayout(self.frame_main_bg)
        self.frame_main_bg_layout.setContentsMargins(5, 5, 5, 5)
        self.frame_main_bg_layout.setSpacing(5)
        self.frame_main_bg_layout.setObjectName("frame_main_bg_layout")
        self.frame_title_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_title_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_title_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_title_bar.setStyleSheet("")
        self.frame_title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title_bar.setObjectName("frame_title_bar")
        self.title_bar_layout = QtWidgets.QHBoxLayout(self.frame_title_bar)
        self.title_bar_layout.setContentsMargins(0, 0, 0, 0)
        self.title_bar_layout.setSpacing(0)
        self.title_bar_layout.setObjectName("title_bar_layout")
        self.frame_title = QtWidgets.QFrame(self.frame_title_bar)
        self.frame_title.setStyleSheet("background-color: none;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.title_layout = QtWidgets.QHBoxLayout(self.frame_title)
        self.title_layout.setContentsMargins(5, 0, 0, 0)
        self.title_layout.setSpacing(0)
        self.title_layout.setObjectName("title_layout")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(52, 217, 182);")
        self.label_title.setObjectName("label_title")
        self.title_layout.addWidget(self.label_title)
        self.title_bar_layout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.frame_title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setStyleSheet("background-color: none;")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.btn_layout = QtWidgets.QHBoxLayout(self.frame_btns)
        self.btn_layout.setContentsMargins(0, 0, 0, 0)
        self.btn_layout.setSpacing(0)
        self.btn_layout.setObjectName("btn_layout")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 170, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 170, 0);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.btn_layout.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_close.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 60, 105);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_layout.addWidget(self.btn_close)
        self.title_bar_layout.addWidget(self.frame_btns)
        self.frame_main_bg_layout.addWidget(self.frame_title_bar)
        self.frame_content_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_content_bar.setAccessibleName("")
        self.frame_content_bar.setStyleSheet("border-radius: 1px;\n"
"")
        self.frame_content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_bar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_content_bar.setLineWidth(1)
        self.frame_content_bar.setMidLineWidth(0)
        self.frame_content_bar.setObjectName("frame_content_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_content_bar)
        self.horizontalLayout.setContentsMargins(-1, 0, 9, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_content_bar)
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(90, 260, 104, 99))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_buttons = QtWidgets.QFrame(self.frame_content_bar)
        self.frame_buttons.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.label = QtWidgets.QLabel(self.frame_buttons)
        self.label.setGeometry(QtCore.QRect(80, 20, 600, 75))
        self.label.setMinimumSize(QtCore.QSize(600, 75))
        self.label.setMaximumSize(QtCore.QSize(600, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_buttons)
        self.label_2.setGeometry(QtCore.QRect(130, 100, 500, 75))
        self.label_2.setMinimumSize(QtCore.QSize(500, 75))
        self.label_2.setMaximumSize(QtCore.QSize(500, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding: 6px;\n"
"mid-width: 10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_buttons)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 171, 761, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkUpBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.checkUpBtn.setMinimumSize(QtCore.QSize(250, 150))
        self.checkUpBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.checkUpBtn.setFont(font)
        self.checkUpBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkUpBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"    color: blue;\n"
"}")
        self.checkUpBtn.setObjectName("checkUpBtn")
        self.gridLayout.addWidget(self.checkUpBtn, 0, 0, 1, 1)
        self.vaccineBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.vaccineBtn.setMinimumSize(QtCore.QSize(250, 150))
        self.vaccineBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.vaccineBtn.setFont(font)
        self.vaccineBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vaccineBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"    color: blue;\n"
"}")
        self.vaccineBtn.setObjectName("vaccineBtn")
        self.gridLayout.addWidget(self.vaccineBtn, 0, 1, 1, 1)
        self.priorityBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.priorityBtn.setMinimumSize(QtCore.QSize(250, 150))
        self.priorityBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.priorityBtn.setFont(font)
        self.priorityBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.priorityBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 42, 62);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(170, 0, 0, 150);\n"
"    color: red;\n"
"}")
        self.priorityBtn.setObjectName("priorityBtn")
        self.gridLayout.addWidget(self.priorityBtn, 1, 1, 1, 1)
        self.dentalBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.dentalBtn.setMinimumSize(QtCore.QSize(250, 150))
        self.dentalBtn.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.dentalBtn.setFont(font)
        self.dentalBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dentalBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138, 155, 197);\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width:1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 6px;\n"
"    mid-width: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(186, 172, 255);\n"
"    color: blue;\n"
"}")
        self.dentalBtn.setObjectName("dentalBtn")
        self.gridLayout.addWidget(self.dentalBtn, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_buttons)
        self.frame_3 = QtWidgets.QFrame(self.frame_content_bar)
        self.frame_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_main_bg_layout.addWidget(self.frame_content_bar)
        self.frame_etc_bar = QtWidgets.QFrame(self.frame_main_bg)
        self.frame_etc_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_etc_bar.setStyleSheet("")
        self.frame_etc_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_etc_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_etc_bar.setObjectName("frame_etc_bar")
        self.etc_layout = QtWidgets.QHBoxLayout(self.frame_etc_bar)
        self.etc_layout.setContentsMargins(0, 0, 0, 5)
        self.etc_layout.setSpacing(0)
        self.etc_layout.setObjectName("etc_layout")
        self.frame_credits = QtWidgets.QFrame(self.frame_etc_bar)
        self.frame_credits.setStyleSheet("background-color: none;")
        self.frame_credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_credits.setObjectName("frame_credits")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_credits)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_credits = QtWidgets.QLabel(self.frame_credits)
        self.label_credits.setStyleSheet("color: rgb(99, 99, 149);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_2.addWidget(self.label_credits)
        self.etc_layout.addWidget(self.frame_credits)
        self.frame_grip = QtWidgets.QFrame(self.frame_etc_bar)
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("background-color: none; padding: 5px; ")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.etc_layout.addWidget(self.frame_grip)
        self.frame_main_bg_layout.addWidget(self.frame_etc_bar)
        self.frame_centralwidget_layout.addWidget(self.frame_main_bg)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Ticket System"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Bagbaguin Health Center and Lying-In Clinic</p></body></html>"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Bagbaguin Health Center"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Bagbaguin Health Center and Lying-In Clinic</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "and Lying - in Clinic"))
        self.checkUpBtn.setText(_translate("MainWindow", "Check Up"))
        self.vaccineBtn.setText(_translate("MainWindow", "Vaccine"))
        self.priorityBtn.setText(_translate("MainWindow", "Priority"))
        self.dentalBtn.setText(_translate("MainWindow", "Dental"))
        self.label_credits.setText(_translate("MainWindow", "Powered By: Python"))

